# Site
repository: sudheer3v/SharePoint2016
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sudheer Akurathi
title: SharePoint & Power Platform Engineer
email: sudheer3v@gmail.com
phone: +1-234-281-8394

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  sudheer3v
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sudheer-akurathi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#- title: SharePoint2016
#  icon: fa-duotone fa-terminal
#  url: github.com/sudheer3v/SharePoint2016


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Sudheer Akurathi. I am an experienced SharePoint/Power Platform Engineer with a proven track record in developing solutions that enhance the functionality of SharePoint and Power Platform. My expertise lies in seamlessly blending technical proficiency with creative problem-solving skills to consistently deliver optimal results for every project. I'm dedicated to crafting customized solutions that empower organizations to collaborate effectively and achieve their business objectives. 
  
  I am highly skilled in <mark>SPFx</mark>, <mark>JavaScript</mark>, <mark>PowerShell</mark>, <mark>C#</mark>, <mark>.NET</mark>, <mark>UI/UX</mark>, <mark>InfoPath Forms</mark>, <mark>Designer Workflows</mark>, <mark>Power Apps</mark>, <mark>Power Automate</mark> and <mark>CSOM</mark>.
  
  In addition, I possess exceptional communication skills and excel in collaborative environments. I work closely with cross-functional teams to understand their requirements, design innovative solutions, and deliver top-quality products.

  Furthermore, I have a successful track record of mentoring junior developers and leading development teams. I maintain a strong commitment to continuous learning, staying current with the latest trends and advancements in the SharePoint field.


  
content:
  - title: Summary # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: SharePoint Online/On-Premise and Power Platform
        link: github.com/sudheer3v/SharePoint2016
        # link_text: Project Website
        additional_links:
          - title:  Power Automate Repository
            icon: fab fa-github
            url: github.com/sudheer3v/PowerAutomate          
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          “I am still learning.” — Michelangelo
        description: | # this will include new lines to allow paragraphs
          - Experienced Microsoft technology professional with 8+ years specializing in SharePoint Online, Office 365, Power Platform, SharePoint Server (on-premises), PowerShell, C#, and .NET Framework. 
          - Proficient in comprehensive content migrations across SharePoint, File Share, and OneDrive using Metalogix, ShareGate, and Microsoft's SPMT. 
          - Skilled in post-migration validation via PowerShell reports and SQL queries. Leveraged SharePoint and Power Platform tools to boost productivity, streamline processes, and foster collaboration. 
          - Expertise in customizing SharePoint sites, workflows, and forms, with strong PowerShell scripting skills for business automation. 
          - Proficient in InfoPath Designer and SharePoint Designer for form and workflow development. 
          - Adept in developing custom SharePoint solutions using SPFx, HTML, CSS, JavaScript, TypeScript, and jQuery, with a focus on intuitive UI/UX design. 
          - Profound expertise in Power Platform development, including Power Apps, Power Automate, and Power BI. 
          - Well-versed in SDLC and source control management tools like GitHub, TFS, and Clear Case. 
          - Exceptional problem-solving skills, collaborating effectively across teams, adaptable to agile and waterfall methodologies.
 


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fifth Third Bank
        link: 53.com
        # link_text: boringcompany.com
        sub_title: Lead SharePoint & Power Platform Engineer
        caption: Oct 2016 - Present
        quote: >
           SPFx Apps; PowerShell Scripting; SharePoint Online Intranet Portal; SharePoint 2016 to SharePoint Online Migration; SharePoint 2007 to 2016 Migration.
        description: | # this will include new lines to allow paragraphs
            - Lead process creation for Shared Drive Transfer and automation of Process Journey to ensure efficiency, speed, uniformity, and quality assurance.
            - Created a self-service Canvas app automating migration decisions, scheduling, site decommissioning, and meeting arrangements, streamlining migration processes. 
            - Developed various Canvas and model-driven apps using Power Apps with Dataverse, replacing InfoPath forms, and enhancing functionalities within SharePoint. 
            - Designed modern portal sites using modern technologies like Teams sites, communication sites, and MS Teams sites, enhancing collaboration. 
            - Developed custom apps such as site alerts, stock tickers, and Forms Library Search Webpart, optimizing communication efficiency within SharePoint. 
            - Led migration processes for SharePoint 2016 data to SharePoint Online and file share data to OneDrive, ensuring seamless data transition.
            - Migrated custom code behind and out-of-the-box (OOTB) workflows into Power Automate using the SPMT Migration Tool. 
            - Developed self-service automation tools, reducing site creation time by 50%. 
            - Created custom site and tenant templates for consistent interface and user experience.
            - Designed a 5-level approval state machine flow, integrating Power Automate with PowerApps and MS Forms, significantly enhancing efficiency. 
            - Designed and developed an intranet portal in SPO utilizing XML templates, PnP PowerShell, and modern technologies, enhancing the user experience, and increasing work efficiency by 30%.
            - Contributed to the SharePoint 2016 upgrade project, successfully migrating 7 TB of SP 2007 data to SP 2016 using METALOGIX and PowerShell.
            - Developed a Provisioning Engine for site creation in SharePoint 2016, enhancing automation. 
            - Generated migration validation reports, ensuring data integrity and successful migrations. 
            - Migrated InfoPath forms from SharePoint 2007 to SharePoint 2016 and integrated them with SharePoint Designer workflows. 
            - Developed a custom central navigation bar and deployed it using JS injection within SharePoint. 
            - Performed quarterly patching on SharePoint 2016 environments, ensuring system stability and security. 
            - Managed Level-3 support and troubleshooting for SharePoint environments.

            
      - layout: left
        title: Crowd Software Consulting LLC
        link: csoftllc.com/
        # link_text: boringcompany.com
        sub_title: SharePoint Developer
        caption: Jan 2016 - Sep 2016
        quote: >
          SharePoint Onpremise Development; SharePoint server maintenance; SharePoint client side development.
        description: | # this will include new lines to allow paragraphs
            - Administered SharePoint 2013 Farm, including Central Administration, Site Collections, Document Libraries, and Lists.
            - Managed site security, permissions, and groups.
            - Worked on mobile and responsive web design for SharePoint Pages.
            - Created and published InfoPath forms to SharePoint.
            - Implemented branding by customizing master pages, themes, and CSS.
            -	Developed custom and OOTB web parts and SharePoint hosted apps.
            -	Created workflows using SharePoint Designer and Visual Studio, integrating them with InfoPath forms for process automation.
            - Utilized PowerShell for automation, administration, and deployment tasks.
            - Developed content types and managed content databases.
            - Monitored and reviewed performance and usage reports.
 



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kent State University
        caption: 2015 
        sub_title: Master of Science (MS) in Computer Science 
        GPA: 3.9/4.0
        quote: >
          Established in 1910, Kent State University is the highest-ranking public university in Northern Ohio on the Top Public Schools and Best National Universities lists in the 2022 U.S.
        description: | # this will include new lines to allow paragraphs
          Worked as a Teaching Assistant for Artificial Intelligence course. Mastered my skills in Programming languages like SQL, JavaScript, HTML, CSS and Python.
    
      - layout: left
        title: JNTU Kakinada
        caption: 2014 
        sub_title: Bachelor of Technology in Computer Science 
        GPA: 3.3/4.0
        description: | # this will include new lines to allow paragraphs
            Got introduced to Computer Science. Leraned skills in Programming languages like SQL, JavaScript, HTML, CSS and Python.

          

  - title: A Little More About My Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Programming Languages:
      - JavaScript (Angular, jQuery, Node, React, Knockout, Gulp)
      - TypeScript, SPFx, .NET, C#, HTML, CSS, REST API, SOAP API, PowerShell, SQL, XML, PHP, Python.

      Tools: 
      - SSMS , SP Designer, InfoPath Designer.
      - PowerApps, PowerAutomate, Power BI, Power Virtual Agents, Power Pages
      - Git, ServiceNow, Tableau.

      
      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
