# Site
repository: sudheer3v/SharePoint2016
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sudheer Akurathi
title: SharePoint & Power Platform Developer
email: sudheer3v@gmail.com
phone: +1-234-281-8394

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  sudheer3v
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sudheer-akurathi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#- title: SharePoint2016
#  icon: fa-duotone fa-terminal
#  url: github.com/sudheer3v/SharePoint2016


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Sudheer Akurathi. I am an experienced SharePoint/Power Platform Engineer with a proven track record in developing solutions that enhance the functionality of SharePoint and Power Platform. My expertise lies in seamlessly blending technical proficiency with creative problem-solving skills to consistently deliver optimal results for every project. I'm dedicated to crafting customized solutions that empower organizations to collaborate effectively and achieve their business objectives. 
  
  I am highly skilled in <mark>SPFx</mark>, <mark>JavaScript</mark>, <mark>PowerShell</mark>, <mark>C#</mark>, <mark>.NET</mark>, <mark>UI/UX</mark>, <mark>InfoPath Forms</mark>, <mark>Designer Workflows</mark>, <mark>Power Apps</mark>, <mark>Power Automate</mark> and <mark>CSOM</mark>.
  
  In addition, I possess exceptional communication skills and excel in collaborative environments. I work closely with cross-functional teams to understand their requirements, design innovative solutions, and deliver top-quality products.

  Furthermore, I have a successful track record of mentoring junior developers and leading development teams. I maintain a strong commitment to continuous learning, staying current with the latest trends and advancements in the SharePoint field.


  
content:
  - title: Summary # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: SharePoint Online/On-Premise and Power Platform
        link: github.com/sudheer3v/SharePoint2016
        # link_text: Project Website
        additional_links:
          - title:  Power Automate Repository
            icon: fab fa-github
            url: github.com/sudheer3v/PowerAutomate          
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          “I am still learning.” — Michelangelo
        description: | # this will include new lines to allow paragraphs
          - Experienced SharePoint & Power Platform Engineer with a demonstrated history of delivering innovative solutions and driving efficiency through Microsoft technologies. 
          - Seeking opportunities to leverage expertise in SharePoint Online, On-premises, and Power Platform Development to optimize processes, streamline workflows, develop efficient solutions, automate business processes, and enhance collaboration within a progressive organization. 
          - Proven track record of leading successful migrations, identifying and resolving complex technical issues and challenges, and automating business processes, resulting in improved efficiency and cost savings. 
          - Committed to leveraging technical skills and problem-solving abilities to achieve project objectives and exceed expectations.
 


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fifth Third Bank
        link: 53.com
        # link_text: boringcompany.com
        sub_title: Lead SharePoint & Power Platform Developer
        caption: Oct 2016 - Present
        quote: >
           SPFx Apps; PowerShell Scripting; SharePoint Online Intranet Portal; SharePoint 2016 to SharePoint Online Migration; SharePoint 2007 to 2016 Migration.
        description: | # this will include new lines to allow paragraphs
        
            •	PowerApps Solutions: Developed and migrated various Canvas and model-driven apps using Power Apps with Dataverse and other connectors to meet specific business requirements like Approval Canvas app that addressing gaps in Power Automate approval flows with additional features like reassignment, reminders, and print capabilities. This also included rebuilding multiple InfoPath Forms into Power Apps.
            •	Power Automate flows: Migrated and developed custom designer workflows and out-of-the-box (OOTB) workflows into Power Automate using SPMT, improving workflow management.
            •	Self-Service Provisioning Engine: Designed and implemented a Self-Service Provisioning Engine in SharePoint, automating custom site creation and reducing site creation time by 50% using Power Shell Scripts, JSON, PowerApps Canvas Apps and Power Automate Flows. 
            •	Process Automation and Efficiency: Spearheaded automated processes for Shared Drive File Transfer, increasing efficiency by 40% and maintaining data integrity using SharePoint Migration Manager and SPMT, standardizing procedures for SharePoint Online, MS Teams, and OneDrive migrations.
            •	Data Management and Reporting: Developed a PowerShell script leveraging parallel processing to scan network shared drives, calculate data sizes, and generate CSV outputs. Integrated this data into Power BI dashboards for executive insights and progress tracking.
            •	SharePoint Migration and Upgrade Management: Directed the migration of 11TB of SharePoint 2016 data to SharePoint Online and automated the migration of 7TB of SharePoint 2007 data to SharePoint 2016, handling 23,000+ site collections using Sharegate, METALOGIX, and PowerShell scripts, ensuring seamless transitions with minimal downtime.
            •	Custom Migration Validation Solutions: Developed PowerShell-based custom migration validation solutions to ensure data integrity and prevent loss during migrations, utilizing database tables, SQL queries, and pre- and post-migration reports.
            •	Intranet Portal and SPFx Development: Led the development of a SharePoint Online Intranet Portal, achieving a 50% increase in user engagement through enhanced UI and customization. Developed SPFx Apps such as Custom Site Alerts, Search Webpart, and Stock Ticker to enhance user productivity.
            •	Custom Development and Governance: Created custom web parts, responsive UI, central navigation bars, page layouts, and design templates in SharePoint 2016 using CSOM, JavaScript, HTML, and CSS. Implemented governance policies to maintain data integrity, compliance, and security within SharePoint environments.
            •	Training, Support, and Maintenance: Conducted "App in a Day" training classes to empower Citizen Developers in creating and managing Canvas Apps and Flows. Delivered SharePoint Level 100 and 200 classes, managed ServiceNow/Remedy work orders and incidents, provided post-migration support, performed quarterly patching on SharePoint 2016, and led an offshore team to ensure operational continuity.


            
      - layout: left
        title: Crowd Software Consulting LLC
        link: csoftllc.com/
        # link_text: boringcompany.com
        sub_title: SharePoint Developer
        caption: Jan 2016 - Sep 2016
        quote: >
          SharePoint Onpremise Development; SharePoint server maintenance; SharePoint client side development.
        description: | # this will include new lines to allow paragraphs
            - Administered SharePoint 2013 Farm, managing Central Administration, Site Collections, Document Libraries, and Lists for optimal performance.
            - Ensured data security and integrity by managing site security, permissions, and groups, implementing robust access controls.
            -	Developed and published InfoPath forms to streamline data capture and workflow automation processes.
            -	Designed and implemented custom web parts, SharePoint hosted apps, and branding strategies to extend functionality and align with organizational branding.
            -	Configured workflows using SharePoint Designer and Visual Studio, integrating them with InfoPath forms for seamless process automation.
            -	Contributed to mobile and responsive web design initiatives for SharePoint Pages to enhance accessibility and user experience.
            -	Utilized PowerShell scripting for automation, administration, and deployment tasks, optimizing operational workflows.
            -	Managed content types and databases to maintain consistency and standardization of content across SharePoint sites.
            -	Monitored performance and usage reports, identifying areas for optimization and improvement in SharePoint usage and performance.

 



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kent State University
        caption: 2015 
        sub_title: Master of Science (MS) in Computer Science 
        GPA: 3.9/4.0
        quote: >
          Established in 1910, Kent State University is the highest-ranking public university in Northern Ohio on the Top Public Schools and Best National Universities lists in the 2022 U.S.
        description: | # this will include new lines to allow paragraphs
          Worked as a Teaching Assistant for Artificial Intelligence course. Mastered my skills in Programming languages like SQL, JavaScript, HTML, CSS and Python.
    
      - layout: left
        title: JNTU Kakinada
        caption: 2014 
        sub_title: Bachelor of Technology in Computer Science 
        GPA: 3.3/4.0
        description: | # this will include new lines to allow paragraphs
            Got introduced to Computer Science. Leraned skills in Programming languages like SQL, JavaScript, HTML, CSS and Python.

          

  - title: A Little More About My Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Programming Languages:
      - JavaScript (Angular, jQuery, Node, React, Knockout, Gulp)
      - TypeScript, SPFx, .NET, C#, HTML, CSS, REST API, SOAP API, PowerShell, SQL, XML, PHP, Python.

      Tools: 
      - SSMS , SP Designer, InfoPath Designer.
      - PowerApps, PowerAutomate, Power BI, Power Virtual Agents, Power Pages
      - Git, ServiceNow, Tableau.

      
      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
