# Site
repository: sudheer3v/SharePoint2016
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sudheer Akurathi
title: SharePoint and Power Platform Engineer
email: sudheer3v@gmail.com
phone: +1-234-281-8394

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  sudheer3v
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sudheer-akurathi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#- title: SharePoint2016
#  icon: fa-duotone fa-terminal
#  url: github.com/sudheer3v/SharePoint2016


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Sudheer Akurathi. I am an experienced SharePoint/Power Platform Engineer with a proven track record in developing solutions that enhance the functionality of SharePoint and Power Platform. My expertise lies in seamlessly blending technical proficiency with creative problem-solving skills to consistently deliver optimal results for every project. I'm dedicated to crafting customized solutions that empower organizations to collaborate effectively and achieve their business objectives. 
  
  I am highly skilled in <mark>SPFx</mark>, <mark>JavaScript</mark>, <mark>PowerShell</mark>, <mark>C#</mark>, <mark>.NET</mark>, <mark>UI/UX</mark>, <mark>InfoPath Forms</mark>, <mark>Designer Workflows</mark>, <mark>Power Apps</mark>, <mark>Power Automate</mark> and <mark>CSOM</mark>.
  
  In addition, I possess exceptional communication skills and excel in collaborative environments. I work closely with cross-functional teams to understand their requirements, design innovative solutions, and deliver top-quality products.

  Furthermore, I have a successful track record of mentoring junior developers and leading development teams. I maintain a strong commitment to continuous learning, staying current with the latest trends and advancements in the SharePoint field.


  
content:
  - title: Summary # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: SharePoint Online/On-Premise and Power Platform
        link: github.com/sudheer3v/SharePoint2016
        # link_text: Project Website
        additional_links:
          - title:  Power Automate Repository
            icon: fab fa-github
            url: github.com/sudheer3v/PowerAutomate          
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          “I am still learning.” — Michelangelo
        description: | # this will include new lines to allow paragraphs
          - Experienced Microsoft technology professional with over 8 years of expertise in SharePoint Online, Office 365, Power Platform, SharePoint Server on-premises, PowerShell, C#, and .NET Framework.
          - Skilled in designing and implementing comprehensive SharePoint, File Share, and OneDrive content migrations using tools like Metalogix, ShareGate, and Microsoft's SPMT.
          - Proficient in conducting post-migration validation through PowerShell reports and SQL queries.
          - Proven track record in leveraging SharePoint's extensive capabilities and Power Platform's suite of tools to drive productivity, streamline business processes, and enhance collaboration across organizations.  
          - Adept at customizing SharePoint sites, workflows, and forms to meet specific business requirements. Possesses excellent PowerShell scripting skills for efficient business automation. 
          - Utilizes InfoPath Designer and SharePoint Designer for form and workflow development. Demonstrated ability in developing sequential and state machine workflows in SharePoint on-premises and SharePoint Online. 
          - Skilled in developing custom SharePoint web parts, extensions, and solutions using SharePoint Framework (SPFx), HTML, CSS, JavaScript, TypeScript, and jQuery. Extensive front-end development experience with a focus on intuitive UI/UX design.          
          - Demonstrated expertise in Power Platform development, including Power Apps, Power Automate (Flow), and Power BI. Designs and implements complex Power Apps solutions, automates workflows, and generates insightful reports and dashboards.          
          - Experienced in the software development life cycle (SDLC) and source control management tools like GitHub, Team Foundation Server (TFS), and Clear Case.          
          - Excellent problem-solving skills and ability to collaborate effectively with cross-functional teams and stakeholders. Adaptable to both waterfall and agile methodologies. 


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fifth Third Bank
        link: 53.com
        # link_text: boringcompany.com
        sub_title: Senior SharePoint/PowerPlatform Developer
        caption: Oct 2016 - Present
        quote: >
           SPFx Apps; PowerShell Scripting; SharePoint Online Intranet Portal; SharePoint 2016 to SharePoint Online Migration; SharePoint 2007 to 2016 Migration.
        description: | # this will include new lines to allow paragraphs
            - Designed and developed a self-service Canvas app that automates the migration process by capturing the user's decision, schedule migrations, decommissions sites, and schedules meetings for further discussion.
            - Developed various Canvas apps and model-driven apps using Power Apps with Dataverse and connectors, replacing InfoPath forms and enhancing form functionalities within SharePoint.              
            - Created modern portal sites such as Teams sites, communication sites, and MS Teams sites, leveraging modern technologies to meet specific business requirements and enhance collaboration and communication within SharePoint.              
            - Developed custom SharePoint Framework (SPFx) apps, including site alerts, hub alerts, stock tickers, and Forms Library Search Webpart, utilizing SPFx, jQuery, JS, HTML, SCSS, TypeScript, Office UI Fabric, and XML templates, optimizing communication efficiency within SharePoint.              
            - Designed, developed, and executed migration processes for migrating SharePoint 2016 data to SharePoint Online (SPO) and file share data to OneDrive, utilizing Sharegate, SPMT Microsoft migration tools, and PowerShell, ensuring seamless data transition.              
            - Migrated custom designer workflows and out-of-the-box (OOTB) workflows into Power Automate using the SPMT Migration Tool, improving workflow management and automation capabilities within SharePoint.              
            - Designed and developed a self-service automation tool called Provisioning Engine, enabling efficient creation of new sites in SPO using PnP PowerShell, Site Designs, Power Automate, and Canvas App, reducing dependency and site creation time by 50%.              
            - Developed custom site templates and tenant templates to enforce a consistent interface, custom navigation, site pages, permissions, themes, and site configuration throughout the SharePoint tenant, ensuring a unified user experience.              
            - Designed and developed a 5-level approval state machine flow in Power Automate, integrated with PowerApps and MS Forms, significantly improving business efficiency by 40% and reducing process time by 20%.              
            - Designed and developed an intranet portal in SPO utilizing XML templates, PnP PowerShell, and modern technologies, enhancing the user experience and increasing work efficiency by 30%.             
            - Participated in SharePoint 2016 upgrade project, automating the SharePoint migration process and successfully migrating 7 TB of SP 2007 data to SP 2016 using the METALOGIX tool and PowerShell.              
            - Developed a Provisioning Engine in SharePoint 2016 that automates the site creation process using Site Request List, InfoPath Form, Designer Workflow, PowerShell modules, and XML Templates.              
            - Developed pre-migration and post-migration reports, SQL queries, and PowerShell scripts for validating the migration process, ensuring data integrity and successful migrations.              
            - Created and configured custom design packages and deployed them to all SP 2016 site collections, ensuring consistent branding and visual identity across the SharePoint environment.              
            - Imported InfoPath forms from SharePoint 2007 to SharePoint 2016 and integrated them with SharePoint Designer workflows, enhancing form functionality and workflow automation.              
            - Developed a custom central navigation bar and deployed it using JS injection and PnP PowerShell, enhancing navigation and user experience within SharePoint.              
            - Performed quarterly patching on SharePoint 2016 production, stage, DR, and development environments, ensuring system stability and security.              
            - Managed Level-3 ServiceNow/Remedy work orders and incidents related to SharePoint 2016, SharePoint Online, and MS Teams, providing efficient support and troubleshooting for SharePoint environments. 
            
      - layout: left
        title: Crowd Software
        link: csoftllc.com/
        # link_text: boringcompany.com
        sub_title: SharePoint Developer
        caption: Jan 2016 - Sep 2016
        quote: >
          SharePoint Onpremise Development; SharePoint server maintenance; SharePoint client side development.
        description: | # this will include new lines to allow paragraphs
            - Developed and administered SharePoint 2013 Farm, including Central Administration, Site Collections, Document Libraries, Lists, and Views.
            - Monitored and reviewed performance and usage reports, managed content databases, and created new ones as required.              
            - Managed security for the site and lists by setting up permissions and permission levels for different users and groups.              
            - Worked on mobile web design and responsive web design of SharePoint Pages.              
            - Created InfoPath 2007/2010 forms and published them to SharePoint.              
            - Implemented SharePoint branding by customizing master pages, themes, and CSS to match corporate branding guidelines.              
            - Created content types for different document libraries with various metadata fields associated with each content type.              
            - Expertise in creating web parts implementation out-of-the-box and custom web parts based on requirements in SharePoint 2013.              
            - Experience in developing SharePoint hosted app parts using Visual Studio 2013, CSOM, and the REST API.              
            - Experience in development with .NET Framework, C#, CSOM (client side), SSOM (server side), and JSOM.              
            - Developed custom code for behind-the-scenes and out-of-the-box workflows using SharePoint Designer and Visual Studio and integrated them with InfoPath forms and automate business processes.              
            - Utilized SharePoint PowerShell cmdlets and scripts for automation, administration, and deployment tasks. 



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kent State University
        caption: 2015 
        sub_title: Master of Science (MS) in Computer Science 
        GPA: 3.9/4.0
        quote: >
          Established in 1910, Kent State University is the highest-ranking public university in Northern Ohio on the Top Public Schools and Best National Universities lists in the 2022 U.S.
        description: | # this will include new lines to allow paragraphs
          Worked as a Teaching Assistant for Artificial Intelligence course. Mastered my skills in Programming languages like SQL, JavaScript, HTML, CSS and Python.
    content:
      - layout: left
          title: JNTU Kakinada
          caption: 2014 
          sub_title: Bachelor of Technology in Computer Science 
          GPA: 3.3/4.0
          description: | # this will include new lines to allow paragraphs
            Got introduced to Computer Science. Leraned skills in Programming languages like SQL, JavaScript, HTML, CSS and Python.

          

  - title: A Little More About My Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Programming Languages:
      - JavaScript (Angular, jQuery, Node, React, Knockout, Gulp)
      - TypeScript, SPFx, .NET, C#, HTML, CSS, REST API, SOAP API, PowerShell, SQL, XML, PHP, Python.

      Tools: 
      - SSMS , SP Designer, InfoPath Designer.
      - PowerApps, PowerAutomate, Power BI, Power Virtual Agents, Power Pages
      - Git, ServiceNow, Tableau.

      
      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
