# Site
repository: sudheer3v/SharePoint2016
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sudheer Akurathi
title: Senior SharePoint/PowerPlatform Developer
email: sudheer3v@gmail.com
phone: +1-234-281-8394

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  sudheer3v
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sudheer-akurathi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#- title: SharePoint2016
#  icon: fa-duotone fa-terminal
#  url: github.com/sudheer3v/SharePoint2016


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sudheer and I'm a senior SharePoint/PowerPlatform Developer. Specialized in designing, developing and maintaining high quality business oriented solutions for SharePoint Online, On premise and O365. 
  
  Most Skilled in <mark>CSOM</mark>, <mark>SPFx</mark>, <mark>JavaScript</mark>, <mark>PowerShell</mark>, <mark>C#</mark>, <mark>.NET</mark>, <mark>UI/UX</mark>, <mark>InfoPath Forms</mark>, <mark>Designer Workflows</mark>, <mark>Power Apps</mark>, and <mark>Power Automate</mark>.
  
  Strong work ethic; Quality of work; Interested in taking up new challenges; Always enthusiastic to learn new things; Taking Initiative and Responsibility.


  
content:
  - title: Summary # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: SharePoint Online/On-Premise and Power Platform
        link: github.com/sudheer3v/SharePoint2016
        # link_text: Project Website
        additional_links:
          - title:  Power Automate Repository
            icon: fab fa-github
            url: github.com/sudheer3v/PowerAutomate          
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          “I am still learning.” — Michelangelo
        description: | # this will include new lines to allow paragraphs
          - More than 6  years of experience in SharePoint Development.
          - Technically strong in SharePoint Online/On Premise, Office 365, MS Teams, Power Platform, InfoPath Forms, and Workflows.
          - Strengths in PowerShell, JavaScript, C#, .NET, and UI/UX.
          - Expert in building custom and highly efficient solutions and apps.
          - Proficient in streamlining repetitive tasks, and developing custom business automations in SPO and SP On premise.
          - Expert in SharePoint content migrations, designing and building complicated electronic forms and workflows.
          - Involved in all phases of SDLC including requirements gathering, analysis, design, development, testing, UAT, production and support.
          - Flexible with Agile and Waterfall methodologies.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fifth Third Bank
        link: 53.com
        # link_text: boringcompany.com
        sub_title: Senior SharePoint/PowerPlatform Developer
        caption: Oct 2016 - Present
        quote: >
          SharePoint 2007 to 2016 Migration; SharePoint Online Intranet Portal; SharePoint 2016 to SharePoint Online Migration.
        description: | # this will include new lines to allow paragraphs
            - Designed and developed an Intranet Portal in SP Online that meet business requirements; is user friendly; is used by 30K+ users daily, by using PnP PowerShell and other modern technologies.
            - Designed and developed an automation process for creating sites in SPO, which runs every hour, every day by using PnP PowerShell and Task Scheduler, this reduced dependency, increased efficiency and saved a lot of time.
            - Developed custom SPFx apps for Site Alerts, Hub Alerts, an app called Stock Ticker to display real time stock prices with 15 min refresh rate, and a custom search web part for libraries to display targeted results in SP Online by using SPFx and other modern technologies.
            - Created interactive and user friendly dashboards and stories to display SharePoint data by using Tableau.
            - Created a 5 level approval State Machine Flow in Power Automate, which improved business efficiency by 40% and increased speed of process by 30%.
            - Led a SharePoint Upgrade project; Migrated 5 TB of SP 2007 data to SP 2016 by using METALOGIX tool and PowerShell Scripts.
            - Developed various reports for permissions, audit and migration validation by using PowerShell, HTML and CSS for both 2007 and 2016 SP Sites.
            - Redesigned the site structure of 1500 SP 2007 sites into 150 Sites in SP 2016 which increased the manageability by 70%.
            - Migrated, re developed and maintained custom / OOTB InfoPath forms and workflows in 07, 13, 16.
      - layout: left
        title: Crowd Software
        link: csoftllc.com/
        # link_text: boringcompany.com
        sub_title: SharePoint Developer
        caption: Oct 2015 - Sep 2016
        quote: >
          SharePoint Onpremise Development; SharePoint server maintenance; SharePoint client side development.
        description: | # this will include new lines to allow paragraphs
            - Designed, Developed and Administered SP 2013 Farm, Central Admin, Site Collections, Sites, Lists and Libraries.
            - Monitored and reviewed the performance/usage reports, created and managed content DB's. 
            - Developed custom master pages and page layouts in SharePoint 2016.
            - Created content types for different document libraries with various metadata fields.
            - Developed training manuals for site content managers, reports related to change management, improvement recommendations, requirements documentation, and project summaries.
            - Performed quarterly SharePoint 2016 patching's to keep all the non prod and prod environments up to date.
            - Developed responsive web designs and custom Nav Bar for all SP 2016 sites; this improved user experience for 30K+ users.
            - Expertise in creating out-of-box and custom web parts based on the requirement in SP 2013.
            - Developed SharePoint hosted App Parts using VS 2013, CSOM and REST API
            - Experience in development with .NET Framework, C#, CSOM (Client Side), SSOM (Server Side), JSOM.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kent State University
        caption: 2014 - 2015 
        sub_title: MSc Computer Science 
        GPA: 3.9/4.0
        quote: >
          Established in 1910, Kent State University is the highest-ranking public university in Northern Ohio on the Top Public Schools and Best National Universities lists in the 2022 U.S.
        description: | # this will include new lines to allow paragraphs
          Worked as a Teaching Assistant for Artificial Intelligence course. Mastered my skills in Programming languages like SQL, JavaScript, HTML, CSS and Python.  

          

  - title: A Little More About My Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Programming Languages:
      - JavaScript (Angular, jQuery, Node, React, Knockout, Gulp)
      - TypeScript, SPFx, .NET, C#, HTML, CSS, REST API, SOAP API, PowerShell, SQL, XML, PHP, Python.

      Tools: 
      - Management Studio, Workflows, InfoPath, PowerApps, PowerAutomate
      - Git, ServiceNow, Tableau, Power BI.

      
      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
