# Site
repository: sudheer3v/SharePoint2016
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sudheer Akurathi
title: Senior SharePoint Developer & PowerPlatform Developer
email: sudheer3v@gmail.com
phone: +1-234-281-8394

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  sudheer3v
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: sudheer-akurathi
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#- title: SharePoint2016
#  icon: fa-duotone fa-terminal
#  url: github.com/sudheer3v/SharePoint2016


# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Sudheer Akurathi and I'm a Senior SharePoint and PowerPlatform Developer. Specialized in designing, developing and maintaining high quality business oriented solutions for SharePoint Online, On premise and O365. 
  
  Most Skilled in <mark>SPFx</mark>, <mark>JavaScript</mark>, <mark>PowerShell</mark>, <mark>C#</mark>, <mark>.NET</mark>, <mark>UI/UX</mark>, <mark>InfoPath Forms</mark>, <mark>Designer Workflows</mark>, <mark>Power Apps</mark>, <mark>Power Automate</mark> and <mark>CSOM</mark>.
  
  Strong work ethic; Quality of work; Interested in taking up new challenges; Always enthusiastic to learn new things; Taking Initiative and Responsibility.


  
content:
  - title: Summary # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: SharePoint Online/On-Premise and Power Platform
        link: github.com/sudheer3v/SharePoint2016
        # link_text: Project Website
        additional_links:
          - title:  Power Automate Repository
            icon: fab fa-github
            url: github.com/sudheer3v/PowerAutomate          
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          “I am still learning.” — Michelangelo
        description: | # this will include new lines to allow paragraphs
          - 6+ years of experience as a Software Engineer in SharePoint Online/On Premise, Power Platform, C#, .NET, PowerShell and Front End Stack.
          - Experienced in SharePoint, File Share, OneDrive migrations using Metalogix, ShareGate and SPMT Microsoft tool.
          - Expert in building custom and highly efficient solutions and apps.
          - Proficient in streamlining repetitive tasks and developing custom business automations in SPO and SP On premise.
          - Proficient in Power Platform Development including Power Apps and Power Automate.
          - Involved in all phases of Software Development Life Cycle.
          - Flexible with Agile and Waterfall methodologies.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Fifth Third Bank
        link: 53.com
        # link_text: boringcompany.com
        sub_title: Senior SharePoint/PowerPlatform Developer
        caption: Oct 2016 - Present
        quote: >
           SPFx Apps; PowerShell Scripting; SharePoint Online Intranet Portal; SharePoint 2016 to SharePoint Online Migration; SharePoint 2007 to 2016 Migration.
        description: | # this will include new lines to allow paragraphs
            - Designed and developed an Intranet Portal in SharePoint Online to replace old portal, improve user experience and efficiency, this helps 30K+ users everyday.
            - Developed a custom SPFx app for site alerts and hub alerts to improve governance and communication.
            - Developed a custom SPFx app called Stock Ticker App to display real time stock details with 15 min refresh settings.
            - Developed a custom search web part app to display targeted results of a library by using SPFx.
            - Designed and developed a self-service automation tool called Provisioning Engine to create new sites in SPO and saved site creation time by 50% and reducing dependency on dev team.
            - Developed multiple custom site templates and tenant templates to enforce consistent interface, navigation, and configuration throughout the tenant.
            - Designed and developed a 5-level approval State Machine Flow in Power Automate and integrated with PowerApps and MS Forms.
            - Migrated content from SharePoint 2016 to SharePoint Online using ShareGate Migration tool. 
            - Migrated content from File Shares to OneDrive using Microsoft SharePoint Migration tool.
            - Worked on SharePoint 2016 Upgrade project; Automated the SharePoint Migrations and Migrated 7 TB of SP 2007 data to SP 2016 by using METALOGIX tool and PowerShell.
            - Developed an automation process to validate migrations by using DB Tables, SQL Queries, and various Pre and Post-Migration PowerShell reports for SP 2007 and SP 2016.
            
      - layout: left
        title: Crowd Software
        link: csoftllc.com/
        # link_text: boringcompany.com
        sub_title: SharePoint Developer
        caption: Jan 2016 - Sep 2016
        quote: >
          SharePoint Onpremise Development; SharePoint server maintenance; SharePoint client side development.
        description: | # this will include new lines to allow paragraphs
            - Created a variety of sites in SharePoint 13, 16 using UI and PowerShell.
            - Customized master pages and page layouts in SharePoint 2016.
            - Migrated custom code behind InfoPath forms from 2007 SharePoint to 2016 SharePoint.
            - Converted custom code behind workflows into SP Designer state machine workflows.
            - Performed SharePoint patching quarterly on SharePoint 2016 servers to keep all the environments up to date.
            - Developed responsive UI and custom Nav Bar for all SP 2016 sites to create central navigation.
            - Developed various reports for permissions, audit and migration validation for SP Sites using PowerShell, HTML and CSS.



  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Kent State University
        caption: 2014 - 2015 
        sub_title: MSc Computer Science 
        GPA: 3.9/4.0
        quote: >
          Established in 1910, Kent State University is the highest-ranking public university in Northern Ohio on the Top Public Schools and Best National Universities lists in the 2022 U.S.
        description: | # this will include new lines to allow paragraphs
          Worked as a Teaching Assistant for Artificial Intelligence course. Mastered my skills in Programming languages like SQL, JavaScript, HTML, CSS and Python.  

          

  - title: A Little More About My Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      Programming Languages:
      - JavaScript (Angular, jQuery, Node, React, Knockout, Gulp)
      - TypeScript, SPFx, .NET, C#, HTML, CSS, REST API, SOAP API, PowerShell, SQL, XML, PHP, Python.

      Tools: 
      - Management Studio, Workflows, InfoPath, PowerApps, PowerAutomate
      - Git, ServiceNow, Tableau, Power BI.

      
      Look at this cool image  
      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
